apiVersion: v1
kind: Service
metadata:
  namespace: user-admin
  name:  user-admin-backend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app:  user-admin-backend